name: Fuream
version: 0.0.1
main: io.github.eat_ram.fuream.FureamMain
api-version: '1.13'
commands:
  fuream:
    description: Fuream plugin management
    permission: fuream.reload
    usage: /<command> [reload|status]
permissions:
  fuream.reload:
    description: Allows reloading Fuream configs
    default: op
